title: <p align="center"> Ashish Singh </p>
logo: /assets/img/ashishsingh.jpg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/ashishsingh88/">LinkedIn</a> |
  <a href="https://github.com/ashish0688">GitHub</a>
  
   
  I build technology products which I would love to use. My expertise is using big data technologies to build security & analytics products. Currently I am working on Data Science, Big Data, Bot Detection & Mitigation, Account Takeover related problems. Working in Security domain for 8+ years.
  </p>


theme: jekyll-theme-minimal
